server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml       # mybatis配置文件所在路径（非必须）
  type-aliases-package: com.liuzhichao.entity               # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept                            #对外暴露微服务的名字（Application列的名称）
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud            # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client:                                                   #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:                                                 
     instance-id: microservicecloud-dept8001               #修改当前服务在eurake中的名称(Status列中的名称)
     prefer-ip-address: true                               #访问路径可以显示IP地址(左下角位置)

info:                                                      #点击超链接可以显示详情信息
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT